Update glue-cicd.yml

diff --git a/.github/workflows/glue-cicd.yml b/.github/workflows/glue-cicd.yml
--- a/.github/workflows/glue-cicd.yml
+++ b/.github/workflows/glue-cicd.yml
@@ -35,55 +35,55 @@ jobs:
         run: |
           aws s3 cp script/data_ingest.py s3://glue-etl-script-00/script/data_ingest.py
 
-      # ---------------------------------
-      # Deploy for Data-Ingestion Glue Job
-      # ---------------------------------
-      - name: Deploy CloudFormation
-        run: |
-          aws cloudformation deploy \
-            --template-file CFT/ingestion_job.yml \
-            --stack-name data-ingestion \
-            --capabilities CAPABILITY_NAMED_IAM
-      # ==========================================
-      # START INGESTION GLUE JOB
-      # ==========================================
-      - name: Start Ingestion Glue Job
-        id: start_ingest
-        run: |
-          INGEST_RUN_ID=$(aws glue start-job-run \
-            --job-name data-ingestion \
-            --region us-east-1 \
-            --query 'JobRunId' \
-            --output text)
+      # # ---------------------------------
+      # # Deploy for Data-Ingestion Glue Job
+      # # ---------------------------------
+      # - name: Deploy CloudFormation
+      #   run: |
+      #     aws cloudformation deploy \
+      #       --template-file CFT/ingestion_job.yml \
+      #       --stack-name data-ingestion \
+      #       --capabilities CAPABILITY_NAMED_IAM
+      # # ==========================================
+      # # START INGESTION GLUE JOB
+      # # ==========================================
+      # - name: Start Ingestion Glue Job
+      #   id: start_ingest
+      #   run: |
+      #     INGEST_RUN_ID=$(aws glue start-job-run \
+      #       --job-name data-ingestion \
+      #       --region us-east-1 \
+      #       --query 'JobRunId' \
+      #       --output text)
 
-          echo "INGEST_RUN_ID=$INGEST_RUN_ID" >> $GITHUB_ENV
+      #     echo "INGEST_RUN_ID=$INGEST_RUN_ID" >> $GITHUB_ENV
 
 
-      # ==========================================
-      # WAIT FOR INGESTION JOB FINISH
-      # ==========================================
-      - name: Wait for ingestion completion
-        run: |
-          while true; do
-            STATUS=$(aws glue get-job-run \
-              --job-name data-ingestion \
-              --run-id $INGEST_RUN_ID \
-              --region us-east-1 \
-              --query 'JobRun.JobRunState' \
-              --output text)
+      # # ==========================================
+      # # WAIT FOR INGESTION JOB FINISH
+      # # ==========================================
+      # - name: Wait for ingestion completion
+      #   run: |
+      #     while true; do
+      #       STATUS=$(aws glue get-job-run \
+      #         --job-name data-ingestion \
+      #         --run-id $INGEST_RUN_ID \
+      #         --region us-east-1 \
+      #         --query 'JobRun.JobRunState' \
+      #         --output text)
 
-            echo "Ingestion status: $STATUS"
+      #       echo "Ingestion status: $STATUS"
 
-            if [ "$STATUS" = "SUCCEEDED" ]; then
-              break
-            fi
+      #       if [ "$STATUS" = "SUCCEEDED" ]; then
+      #         break
+      #       fi
 
-            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then
-              exit 1
-            fi
+      #       if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then
+      #         exit 1
+      #       fi
 
-            sleep 30
-          done
+      #       sleep 30
+      #     done
 
       # ==========================================
       # UPLOAD SCRIPT
